seed: 42
device: cuda
num_envs: 2
env_name: extrange_robot.tasks.direct.extrange_robot.extrange_robot_env_cfg:ExtrangeRobotEnvCfg

train:
  algorithm: ppo
  total_iterations: 5000
  max_iterations_per_env: 1000
  log_interval: 10
  save_interval: 100
  eval_interval: 50

ppo:
  actor_lr: 0.0003
  critic_lr: 0.001
  discount_factor: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  entropy_coef: 0.01
  value_loss_coef: 2.0
  num_mini_batches: 4
  num_learning_epochs: 4
  rollout_length: 24