seed: 42
device: cuda:0
num_steps_per_env: 32
max_iterations: 1001
empirical_normalization: false
policy:
  class_name: ActorCritic
  init_noise_std: 2.0
  noise_std_type: scalar
  actor_hidden_dims:
  - 64
  - 64
  critic_hidden_dims:
  - 64
  - 64
  activation: elu
algorithm:
  class_name: PPO
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 0.0003
  schedule: adaptive
  gamma: 0.99
  lam: 0.95
  entropy_coef: 0.01
  desired_kl: 0.005
  max_grad_norm: 1.0
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  normalize_advantage_per_mini_batch: false
  symmetry_cfg: null
  rnd_cfg: null
clip_actions: null
save_interval: 100
experiment_name: extrange_robot_ppo
run_name: extrange_run
logger: tensorboard
neptune_project: isaaclab
wandb_project: isaaclab
resume: true
load_run: 2025-06-21_21-21-41_extrange_run
load_checkpoint: model_.*.pt
